language: go
go:
    - tip
before_install:
    - "cd $TRAVIS_BUILD_DIR"
    - ./script/dependence.sh
    - ./script/unittest.sh

script:
    - $HOME/gopath/bin/websimple

after_failure:
    - "cd $TRAVIS_BUILD_DIR"

